import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { plannerFixture } from './revision-v2-fixture.mjs';
import { MemoryRepository, fileLoader, fileFetch } from './helpers.mjs';
import { SchemaRegistry } from '../src/lib/schemaValidator.js';
import { productFoodReferenceTerms } from '../src/domain/productFoodTaxonomy.js';
import { extensionDefaults, extensionPreferenceScore, deductPantry, estimateShoppingCost, validateBatchLinks, EXTENSION_STORES } from '../src/domain/productExtensions.js';
import { saveExtensionSettings, loadProductExtensions, setRecipeFavorite, setMealLocked, saveMenu, createMenuPreview, commitMenuPreview, savePantryEntry, saveSeasonalityProfile, saveIngredientPrice, createBatchPreview, commitBatchPreview, deleteProductionBatch } from '../src/services/productExtensionService.js';
import { createInitialPreview, commitGeneratedPreview, createRebalancePreview, commitRebalancePreview, undoPlanOperation, redoPlanOperation } from '../src/services/effectivePlanService.js';
import { calculateShoppingList, buildPreparationHorizon, createShoppingChecklist, shoppingText } from '../src/services/shoppingService.js';
import { countFrequencyWindow } from '../src/domain/frequencyCounter.js';
import { blankFrequencyRule } from '../src/domain/legacyRuleAdapter.js';
import { createBackup, importBackup, validateBackup } from '../src/services/backupEngine.js';
import { CatalogQueryService } from '../src/services/catalogQuery.js';
import { CatalogImporter } from '../src/services/catalogImporter.js';
import { ensureBootstrapConfiguration } from '../src/services/configurationBootstrap.js';
import { snapshotRepository } from '../src/services/portableBackup.js';
import { sha256Json } from '../src/lib/crypto.js';
const start='2026-09-11',end='2026-09-14';
async function planned({v2=false}={}) {
  const ctx=await plannerFixture(),{repo}=ctx;
  for(const rev of await repo.getAll('ingredientRevisions')){rev.i18n={it:{name:'SYNTHETIC '+rev.ingredientId},en:{name:'SYNTHETIC '+rev.ingredientId}};await repo.put('ingredientRevisions',rev);}
  for(const ingredientId of ['ing_oats','ing_chicken','ing_night','ing_fish'])await repo.put('ingredients',{ingredientId,currentRevisionId:(await repo.getAll('ingredientRevisions')).find(r=>r.ingredientId===ingredientId).ingredientRevisionId,status:'active'});
  const cycle=await repo.get('cycles','cycle');cycle.length=1;cycle.days=[cycle.days[0]];await repo.put('cycles',cycle);
  // One dinner candidate makes batch identity exact without mutating any frozen recipe.
  const family=await repo.get('recipes','r_chicken2');family.status='archived';await repo.put('recipes',family);
  if(v2)await repo.put('foodPreferences',{schemaVersion:2,id:'prefs',rules:[]});
  const preview=await createInitialPreview({horizon:{startDate:start,endDate:end},seed:'r8-fixture'},ctx);assert.equal(preview.status,'success',JSON.stringify(preview.failure));await commitGeneratedPreview(preview,ctx);
  return {...ctx,planId:preview.planInstance.planInstanceId,days:await repo.getAll('calendarDays')};
}
function batchDraft(ctx,overrides={}) {return {planInstanceId:ctx.planId,recipeVersionId:'rv_chicken',portionsProduced:4,productionDate:start,assignments:ctx.days.map(day=>({calendarDayId:day.calendarDayId,mealOccurrenceId:day.mealSlots.find(s=>s.mealClassId==='mc-dinner').mealOccurrenceId,componentIndex:0})),...overrides};}
async function addForms(ctx){const terms=productFoodReferenceTerms();await ctx.repo.putMany('taxonomyTerms',terms);const concept=terms.find(t=>t.termId==='product_concept_chicken');assert.ok(concept);const revisions=await ctx.repo.getAll('ingredientRevisions');for(const rev of revisions.filter(r=>r.ingredientId==='ing_chicken')){rev.productTaxonomy={conceptId:concept.termId,categoryId:'product_category_poultry',subcategoryId:concept.parentTermId};await ctx.repo.put('ingredientRevisions',rev);}await ctx.repo.put('ingredients',{ingredientId:'ing_chicken',currentRevisionId:'rev_chicken_r_chicken',status:'active'});return concept.termId;}
test('T66 favorite persistence and query use recipe family identity; optional weight zero leaves score unchanged',async()=>{const ctx=await planned();await setRecipeFavorite('r_chicken',true,ctx);const query=new CatalogQueryService({repo:ctx.repo});const result=await query.searchRecipes({favoritesOnly:true});assert.deepEqual(result.items.map(r=>r.recipeId),['r_chicken']);const recipe=await ctx.repo.get('recipeVersions','rv_chicken'),extensions=await loadProductExtensions(ctx.repo);assert.equal(extensionPreferenceScore(recipe,{extensions,date:start,revisionById:new Map()}).score,0);await saveExtensionSettings({...extensionDefaults(),favoriteWeight:5},ctx);assert.equal(extensionPreferenceScore(recipe,{extensions:await loadProductExtensions(ctx.repo),date:start,revisionById:new Map()}).score,-5);await setRecipeFavorite('r_chicken',false,ctx);assert.equal((await query.searchRecipes({favoritesOnly:true})).total,0);});
test('T66 locked meal survives rebalance unchanged in legacy and frequency engine',async()=>{for(const v2 of [false,true]){const ctx=await planned({v2}),day=ctx.days[0],slot=day.mealSlots[0];await setMealLocked({calendarDayId:day.calendarDayId,mealOccurrenceId:slot.mealOccurrenceId,locked:true},ctx);const original=(await ctx.repo.get('calendarDays',day.calendarDayId)).mealSlots[0];const preview=await createRebalancePreview({planInstanceId:ctx.planId,startDate:start,endDate:start,seed:'r8-other'},ctx);assert.equal(preview.status,'success',JSON.stringify(preview.failure));assert.deepEqual(preview.calendarDays[0].mealSlots[0],original);await commitRebalancePreview(preview,ctx);assert.deepEqual((await ctx.repo.get('calendarDays',day.calendarDayId)).mealSlots[0],original);}});
test('T66 a lock never authorizes a newly excluded food; failed rebalance leaves plan intact and explicit unlock is possible',async()=>{const ctx=await planned(),day=ctx.days[0],slot=day.mealSlots[0];await setMealLocked({calendarDayId:day.calendarDayId,mealOccurrenceId:slot.mealOccurrenceId,locked:true},ctx);await ctx.repo.put('allergyIntoleranceProfiles',{schemaVersion:2,id:'allergy',rules:[{id:'new',kind:'allergy',target:{type:'ingredient',id:'ing_oats'},enabled:true,notes:'',effectiveFrom:'2026-09-01'}]});const before=await ctx.repo.getAll('calendarDays');const preview=await createRebalancePreview({planInstanceId:ctx.planId,startDate:start,endDate:start},ctx);assert.notEqual(preview.status,'success');assert.deepEqual(await ctx.repo.getAll('calendarDays'),before);await setMealLocked({calendarDayId:day.calendarDayId,mealOccurrenceId:slot.mealOccurrenceId,locked:false},ctx);assert.equal((await ctx.repo.get('calendarDays',day.calendarDayId)).mealSlots[0].locked,false);});
test('T67 menu snapshots omit notes, adherence, locks and batch links; apply recalculates nutrition on new dates and supports undo',async()=>{const ctx=await planned();const day=ctx.days[0];day.mealSlots[0].adherenceStatus='followed';day.mealSlots[0].adherenceNotes='SYNTHETIC PRIVATE';await ctx.repo.put('calendarDays',day);const menu=await saveMenu({name:'SYNTHETIC MENU',planInstanceId:ctx.planId,startDate:start,endDate:start},ctx);assert.doesNotMatch(JSON.stringify(menu),/SYNTHETIC PRIVATE|adherence|locked|productionBatch/);const before=await ctx.repo.get('calendarDays',ctx.days[2].calendarDayId);const preview=await createMenuPreview({menuId:menu.menuId,planInstanceId:ctx.planId,startDate:'2026-09-13'},ctx);assert.equal(preview.calendarDays[0].date,'2026-09-13');assert.equal(preview.calendarDays[0].mealSlots[0].adherenceNotes,null);assert.equal(preview.calendarDays[0].mealSlots[0].adherenceStatus,'not_recorded');await commitMenuPreview(preview,ctx);const updated=await ctx.repo.get('calendarDays',before.calendarDayId);const expected=updated.mealSlots.flatMap(s=>s.recipeComponents);const nutrition=(await ctx.repo.getMany('recipeVersions',expected.map(c=>c.recipeVersionId))).reduce((n,r)=>n+r.calculatedNutrition.energyKcal,0);assert.equal(updated.nutritionSummary.knownPlanned.energyKcal,nutrition);await undoPlanOperation(ctx.planId,ctx);assert.deepEqual(await ctx.repo.get('calendarDays',before.calendarDayId),before);});
test('T67 menu preview rejects locked destinations and later settings edits invalidate confirmation',async()=>{const ctx=await planned();const menu=await saveMenu({name:'SYNTHETIC',planInstanceId:ctx.planId,startDate:start,endDate:start},ctx);const draft={menuId:menu.menuId,planInstanceId:ctx.planId,startDate:'2026-09-13'};const preview=await createMenuPreview(draft,ctx);await saveExtensionSettings({...extensionDefaults(),favoriteWeight:2},ctx);await assert.rejects(commitMenuPreview(preview,ctx),error=>error.code==='stale_preview');const day=ctx.days[2];await setMealLocked({calendarDayId:day.calendarDayId,mealOccurrenceId:day.mealSlots[0].mealOccurrenceId,locked:true},ctx);await assert.rejects(createMenuPreview(draft,ctx),/Sblocca/);});
test('T67 concurrent source edit rejects menu saving rather than capturing stale assignments',async()=>{const ctx=await planned();const original=ctx.repo.atomicMutate.bind(ctx.repo);ctx.repo.atomicMutate=async mutation=>{if(mutation.puts?.savedMenus){const day=await ctx.repo.get('calendarDays',ctx.days[0].calendarDayId);day.updatedAt='2099-01-01T00:00:00Z';await ctx.repo.put('calendarDays',day);}return original(mutation);};await assert.rejects(saveMenu({name:'SYNTHETIC',planInstanceId:ctx.planId,startDate:start,endDate:start},ctx),/oncurrent/);assert.equal(await ctx.repo.count('savedMenus'),0);});
test('T68 unknown, absent, expired, generic and unselected pantry entries never reduce quantities',()=>{const items=[{itemId:'a',ingredientId:'x',unit:'g',quantity:100,_state:'dry'}];const base={entryId:'p',ingredientId:'x',available:true,quantity:70,unit:'g',expiresOn:null};for(const patch of [{quantity:null},{available:false},{expiresOn:'2026-09-10'},{ingredientId:null}])assert.equal(deductPantry(items,{entries:[{...base,...patch}],selectedIds:['p'],endDate:end}).items[0].quantity,100);assert.equal(deductPantry(items,{entries:[base],endDate:end}).items[0].quantity,100);});
test('T68 finite pantry pool is deducted once, never across incompatible historical states',()=>{const items=[{itemId:'a',ingredientId:'x',unit:'g',quantity:50,_state:'dry'},{itemId:'b',ingredientId:'x',unit:'g',quantity:100,_state:'dry'}];const entries=[{entryId:'p',ingredientId:'x',available:true,quantity:70,unit:'g'}];let result=deductPantry(items,{entries,selectedIds:['p','p'],endDate:end});assert.equal(result.items[0].quantity,80);assert.equal(result.usage.reduce((n,u)=>n+u.amount,0),70);items[1]._state='cooked';result=deductPantry(items,{entries,selectedIds:['p'],endDate:end,stateByIngredient:new Map([['x','dry']])});assert.equal(result.items[0].quantity,100);assert.equal(result.usage.reduce((n,u)=>n+u.amount,0),50);});
test('T68 form-aware pantry quantity persists and only explicit selection changes shopping; checklist export declares deduction',async()=>{const ctx=await planned(),conceptId=await addForms(ctx);const entry=await savePantryEntry({conceptId,ingredientId:'ing_chicken',available:true,quantity:150,unit:'g'},ctx);const range={startCivilDate:start,endCivilDate:end,peopleMultiplier:1};const baseline=await calculateShoppingList(range,ctx);await saveExtensionSettings({...extensionDefaults(),pantryEntryIds:[entry.entryId]},ctx);const next=await calculateShoppingList(range,ctx);assert.equal(baseline.items.find(i=>i.ingredientId==='ing_chicken').quantity-next.items.find(i=>i.ingredientId==='ing_chicken').quantity,150);assert.equal((await ctx.repo.get('pantryEntries',entry.entryId)).quantity,150);const list=await createShoppingChecklist(range,ctx);assert.match(shoppingText(list),/dispensa/);await assert.rejects(savePantryEntry({conceptId,available:true,quantity:10,unit:'g'},ctx),/forma/);});
test('T69 four allocated portions produce one shopping production and four frequency occurrences; undo and redo restore links',async()=>{const ctx=await planned();const before=await ctx.repo.getAll('calendarDays');const preview=await createBatchPreview(batchDraft(ctx),ctx);await commitBatchPreview(preview,ctx);const range={startCivilDate:start,endCivilDate:end,peopleMultiplier:1},list=await calculateShoppingList(range,ctx);const chicken=list.items.find(i=>i.ingredientId==='ing_chicken');assert.equal(chicken.quantity,400);assert.equal(chicken.sourceMealOccurrenceIds.length,1);assert.match(chicken.sourceMealOccurrenceIds[0],/^production:/);assert.equal(list.batchConsumptionCount,4);const later=await calculateShoppingList({...range,startCivilDate:'2026-09-12'},ctx);assert.equal(later.items.some(i=>i.ingredientId==='ing_chicken'),false);const days=await ctx.repo.getAll('calendarDays');const rule={...blankFrequencyRule('r','2026-09-11'),window:{kind:'rolling',days:4},target:{type:'ingredient',id:'ing_chicken'},minOccurrences:0,targetOccurrences:4,maxOccurrences:4};const count=countFrequencyWindow(rule,end,{calendarDays:days,recipesByVersion:new Map((await ctx.repo.getAll('recipeVersions')).map(r=>[r.recipeVersionId,r])),revisionById:new Map((await ctx.repo.getAll('ingredientRevisions')).map(r=>[r.ingredientRevisionId,r]))});assert.equal(count.count,4);assert.ok(days.flatMap(d=>d.mealSlots.flatMap(s=>s.recipeComponents)).every(c=>c.servings===1));const prep=await buildPreparationHorizon(range,ctx);assert.equal(prep.entries.filter(e=>e.batchId).length,1);assert.equal(prep.entries.find(e=>e.batchId).totalMinutes,null);await undoPlanOperation(ctx.planId,ctx);assert.deepEqual(await ctx.repo.getAll('calendarDays'),before);assert.equal(await ctx.repo.count('productionBatches'),0);await redoPlanOperation(ctx.planId,ctx);assert.deepEqual(await ctx.repo.getAll('calendarDays'),days);assert.equal(await ctx.repo.count('productionBatches'),1);});
test('T69 batch refuses over-allocation, duplicate meals, consumption before production and undocumented shelf life',async()=>{const ctx=await planned();for(const patch of [{portionsProduced:3},{productionDate:end},{storage:{status:'unverified',useByDate:end,sourceRef:'invented'}},{storage:{status:'documented',useByDate:'2026-09-12',sourceRef:'SYNTHETIC TEST'}}])await assert.rejects(createBatchPreview(batchDraft(ctx,patch),ctx));const draft=batchDraft(ctx);draft.assignments.push(draft.assignments[0]);await assert.rejects(createBatchPreview(draft,ctx));assert.equal(await ctx.repo.count('productionBatches'),0);});
test('T69 batch-assigned meals survive rebalance, explicit detach is undoable',async()=>{const ctx=await planned();const preview=await createBatchPreview(batchDraft(ctx),ctx);await commitBatchPreview(preview,ctx);const next=await createRebalancePreview({planInstanceId:ctx.planId,startDate:start,endDate:start,mode:'recalculate'},ctx);assert.equal(next.status,'success',JSON.stringify(next.failure));await commitRebalancePreview(next,ctx);const batch=(await ctx.repo.getAll('productionBatches'))[0];validateBatchLinks(batch,await ctx.repo.getAll('calendarDays'),new Map((await ctx.repo.getAll('recipeVersions')).map(r=>[r.recipeVersionId,r])));await deleteProductionBatch(batch.batchId,ctx);assert.equal(await ctx.repo.count('productionBatches'),0);await undoPlanOperation(ctx.planId,ctx);assert.equal(await ctx.repo.count('productionBatches'),1);});
test('T70 seasonality requires selected area and documented months; no universal calendar or hard override',async()=>{const ctx=await planned(),conceptId=await addForms(ctx);const profile=await saveSeasonalityProfile({name:'SYNTHETIC AREA',entries:[{conceptId,months:[9],sourceRef:'SYNTHETIC TEST ONLY',reviewedAt:start}]},ctx);const recipe=await ctx.repo.get('recipeVersions','rv_chicken'),revisionById=new Map((await ctx.repo.getAll('ingredientRevisions')).map(r=>[r.ingredientRevisionId,r]));assert.equal(extensionPreferenceScore(recipe,{extensions:await loadProductExtensions(ctx.repo),date:start,revisionById}).score,0);await saveExtensionSettings({...extensionDefaults(),seasonalityProfileId:profile.profileId,seasonalityWeight:3},ctx);const extensions=await loadProductExtensions(ctx.repo);assert.equal(extensionPreferenceScore(recipe,{extensions,date:start,revisionById}).score,-3);assert.equal(extensionPreferenceScore(recipe,{extensions,date:'2026-10-01',revisionById}).score,0);await assert.rejects(saveSeasonalityProfile({name:'bad',entries:[{conceptId,months:[9],sourceRef:' ',reviewedAt:start}]},ctx));});
test('T70 costs distinguish missing, explicit zero, incompatible unit/currency, future and stale prices; budget stays unknown when incomplete',()=>{const items=[{itemId:'a',ingredientId:'x',unit:'g',quantity:100},{itemId:'b',ingredientId:'y',unit:'g',quantity:100}];const price={priceId:'p',ingredientId:'x',quantity:1000,price:20,unit:'g',currency:'EUR',observedOn:'2026-01-01',updatedAt:start,sourceRef:'SYNTHETIC TEST ONLY'};let cost=estimateShoppingCost(items,[price],{asOf:start,budget:5});assert.equal(cost.total,null);assert.equal(cost.knownSubtotal,2);assert.equal(cost.budgetStatus,'unknown');assert.equal(cost.lines[0].stale,true);cost=estimateShoppingCost(items,[price,{...price,priceId:'p2',ingredientId:'y',price:0}],{asOf:start,budget:5});assert.equal(cost.total,2);assert.equal(cost.budgetStatus,'within');for(const patch of [{currency:'USD'},{unit:'ml'},{observedOn:end}])assert.equal(estimateShoppingCost(items,[{...price,...patch}],{asOf:start}).knownSubtotal,0);});
test('T68 explicit reviewed directional conversion is required to deduct a different pantry form',()=>{const items=[{itemId:'a',ingredientId:'dry',unit:'g',quantity:100,_state:'dry'}];const entry={entryId:'p',ingredientId:'cooked',unit:'g',quantity:100,available:true};const edge={conversionId:'synthetic-yield',version:1,fromIngredientId:'cooked',toIngredientId:'dry',fromUnit:'g',toUnit:'g',factor:.4,purpose:'shopping_yield',sourceRef:'SYNTHETIC TEST ONLY',reviewStatus:'reviewed'};const options={entries:[entry],selectedIds:['p'],endDate:end,conversions:[edge]};assert.equal(deductPantry(items,options).items[0].quantity,100);options.choices=[{fromIngredientId:'cooked',fromUnit:'g',conversionId:edge.conversionId,version:1}];assert.equal(deductPantry(items,options).items[0].quantity,60);edge.reviewStatus='unreviewed';assert.equal(deductPantry(items,options).items[0].quantity,100);});
test('T66/T70 maximum soft weights never admit an allergy-excluded favorite recipe',async()=>{const ctx=await planned();await setRecipeFavorite('r_fish',true,ctx);await saveExtensionSettings({...extensionDefaults(),favoriteWeight:5,seasonalityWeight:5},ctx);const preview=await createRebalancePreview({planInstanceId:ctx.planId,startDate:start,endDate:end},ctx);assert.equal(preview.status,'success');assert.ok(preview.calendarDays.flatMap(d=>d.mealSlots.flatMap(s=>s.recipeComponents)).every(c=>c.recipeId!=='r_fish'));});
test('T67 menu refuses outdated recipe version without mutating its source model',async()=>{const ctx=await planned();const menu=await saveMenu({name:'SYNTHETIC',planInstanceId:ctx.planId,startDate:start,endDate:start},ctx);const family=await ctx.repo.get('recipes',menu.days[0].slots[0].components[0].recipeId);family.status='archived';await ctx.repo.put('recipes',family);await assert.rejects(createMenuPreview({menuId:menu.menuId,planInstanceId:ctx.planId,startDate:end},ctx),/versione non corrente/);assert.deepEqual(await ctx.repo.get('savedMenus',menu.menuId),menu);});
test('T66–T70 backup v4 roundtrips six extension stores, settings and batch undo; v3 migrates to empty defaults; malformed extension history rejects atomically',async()=>{
  const registry=new SchemaRegistry(fileLoader(path.join(process.cwd(),'schemas')));await registry.loadAll();const repo=new MemoryRepository(),fetcher=fileFetch(path.join(process.cwd(),'public'));const ctx={repo,registry};await new CatalogImporter({repo,registry,fetcher,storage:null}).bootstrap();await ensureBootstrapConfiguration({repo,registry,fetcher});
  const legacy=await createBackup(ctx);legacy.formatVersion=3;for(const store of EXTENSION_STORES)delete legacy.payload.portableSnapshot[store];legacy.sha256=await sha256Json({...legacy,sha256:null});const empty=new MemoryRepository();await importBackup(legacy,{repo:empty,registry});for(const store of EXTENSION_STORES)assert.equal(await empty.count(store),0);assert.deepEqual((await loadProductExtensions(empty)).settings,extensionDefaults());
  const preview=await createInitialPreview({horizon:{startDate:start,endDate:start},seed:'r8-backup'},ctx);assert.equal(preview.status,'success',JSON.stringify(preview.failure));await commitGeneratedPreview(preview,ctx);const day=preview.calendarDays[0],slot=day.mealSlots.find(s=>s.mode==='planned'),component=slot.recipeComponents[0];const ingredient=(await repo.getAll('ingredients')).find(f=>f.status==='active');const form=await repo.get('ingredientRevisions',ingredient.currentRevisionId);assert.ok(form.productTaxonomy?.conceptId);
  await setRecipeFavorite(component.recipeId,true,ctx);await saveMenu({name:'SYNTHETIC MENU',planInstanceId:day.planInstanceId,startDate:start,endDate:start},ctx);const pantry=await savePantryEntry({conceptId:form.productTaxonomy.conceptId,ingredientId:ingredient.ingredientId,available:true,quantity:250,unit:'g',expiresOn:end},ctx);const area=await saveSeasonalityProfile({name:'SYNTHETIC AREA',entries:[{conceptId:form.productTaxonomy.conceptId,months:[9],sourceRef:'SYNTHETIC TEST ONLY',reviewedAt:start}]},ctx);await saveIngredientPrice({ingredientId:ingredient.ingredientId,price:2.3,quantity:1000,unit:'g',currency:'EUR',observedOn:start,sourceRef:'SYNTHETIC TEST ONLY'},ctx);await saveExtensionSettings({...extensionDefaults(),favoriteWeight:2,seasonalityProfileId:area.profileId,seasonalityWeight:1,pantryEntryIds:[pantry.entryId],shoppingBudget:50},ctx);
  const bp=await createBatchPreview({planInstanceId:day.planInstanceId,recipeVersionId:component.recipeVersionId,portionsProduced:4,productionDate:start,assignments:[{calendarDayId:day.calendarDayId,mealOccurrenceId:slot.mealOccurrenceId,componentIndex:0}]},ctx);await commitBatchPreview(bp,ctx);
  const backup=await createBackup(ctx);assert.equal(backup.formatVersion,4);assert.equal(Object.keys(backup.payload.portableSnapshot).length,31);const dest=new MemoryRepository();await importBackup(backup,{repo:dest,registry});for(const store of EXTENSION_STORES)assert.deepEqual(await dest.getAll(store),await repo.getAll(store));assert.deepEqual(await dest.getMeta('productExtensions:R8'),await repo.getMeta('productExtensions:R8'));await undoPlanOperation(day.planInstanceId,{repo:dest,registry});assert.equal(await dest.count('productionBatches'),0);await redoPlanOperation(day.planInstanceId,{repo:dest,registry});assert.equal(await dest.count('productionBatches'),1);
  const bad=structuredClone(backup);bad.payload.portableSnapshot.operations.find(op=>op.kind==='batch_create').after.puts.productionBatches[0].assignments[0].civilDate=end;bad.sha256=await sha256Json({...bad,sha256:null});const before=await snapshotRepository(dest);await assert.rejects(importBackup(bad,{repo:dest,registry}),/Batch/);assert.deepEqual(await snapshotRepository(dest),before);
  const orphan=structuredClone(backup);orphan.payload.portableSnapshot.savedMenus[0].days[0].slots[0].components[0].recipeVersionId='orphan';orphan.sha256=await sha256Json({...orphan,sha256:null});await assert.rejects(validateBackup(orphan,{repo:dest,registry}),/Orphan/);
  const {runMigrations}=await import('../src/services/migrationRunner.js');await repo.setMeta('contentSchemaVersion',4);await runMigrations(repo,{registry});const extensions=await loadProductExtensions(repo);await runMigrations(repo,{registry});assert.deepEqual(await loadProductExtensions(repo),extensions);assert.equal(await repo.getMeta('contentSchemaVersion'),5);assert.equal(await repo.getMeta('dbVersion'),9);
});
