import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { MemoryRepository, fileLoader, fileFetch } from './helpers.mjs';
import { SchemaRegistry } from '../src/lib/schemaValidator.js';
import { CatalogImporter } from '../src/services/catalogImporter.js';
import { ensureBootstrapConfiguration } from '../src/services/configurationBootstrap.js';
import { createBackup, importBackup, validateBackup } from '../src/services/backupEngine.js';
import { snapshotRepository, parseBackupText } from '../src/services/portableBackup.js';
import { sha256Json } from '../src/lib/crypto.js';
import { createLocalDiagnostics, safeExternalUrl } from '../src/services/localDiagnostics.js';
import { calculateShoppingList, createShoppingChecklist, updateShoppingChecklistItem, addManualShoppingItem, refreshShoppingChecklist, shoppingChecklistStaleness, saveShoppingSettings, getShoppingSettings, shoppingText } from '../src/services/shoppingService.js';
async function registry(){const r=new SchemaRegistry(fileLoader(path.join(process.cwd(),'schemas')));await r.loadAll();return r;}
async function catalog(){const repo=new MemoryRepository(),r=await registry(),fetcher=fileFetch(path.join(process.cwd(),'tests/fixtures/catalog-0.3'));await new CatalogImporter({repo,registry:r,fetcher,storage:null}).bootstrap();await ensureBootstrapConfiguration({repo,registry:r,fetcher});return {repo,registry:r};}
async function shopping(){const repo=new MemoryRepository();await repo.put('planInstances',{planInstanceId:'p',updatedAt:'2026-09-01T00:00:00Z'});await repo.setMeta('activePlanInstanceId','p');
for(const [id,state] of [['dry','dry'],['cooked','cooked']]){await repo.put('ingredients',{ingredientId:id,currentRevisionId:id+'r'});await repo.put('ingredientRevisions',{ingredientId:id,ingredientRevisionId:id+'r',basis:{state},productTaxonomy:{conceptId:'millet',categoryId:'cereals'},i18n:{it:{name:'Miglio'},en:{name:'Millet'}}});}
await repo.put('recipeVersions',{recipeVersionId:'v',ingredientLines:[{ingredientId:'dry',ingredientRevisionId:'dryr',normalizedAmount:100,normalizedUnit:'g'},{ingredientId:'cooked',ingredientRevisionId:'cookedr',normalizedAmount:150,normalizedUnit:'g'}]});
await repo.put('calendarDays',{calendarDayId:'d',planInstanceId:'p',date:'2026-09-11',mealSlots:[{mealOccurrenceId:'m',civilDate:'2026-09-11',time:'12:00',mode:'planned',recipeComponents:[{recipeVersionId:'v',servings:1}]},{mealOccurrenceId:'external',civilDate:'2026-09-11',time:'20:00',mode:'external',recipeComponents:[]}]});
await repo.put('ingredientConversions',{schemaVersion:1,conversionId:'yield',version:1,fromIngredientId:'cooked',toIngredientId:'dry',fromUnit:'g',toUnit:'g',factor:0.4,purpose:'shopping_yield',sourceRef:'SYNTHETIC TEST ONLY — not a nutritional recommendation',reviewStatus:'reviewed'});
return {repo,registry:await registry()};}
const range={startCivilDate:'2026-09-11',endCivilDate:'2026-09-11',peopleMultiplier:1};
const choice={fromIngredientId:'cooked',fromUnit:'g',conversionId:'yield',version:1};
test('R6 T19/T57 explicit directional purchase yield groups 100 dry + 150 cooked into 160 dry, plan unchanged',async()=>{const {repo}=await shopping();const before=await repo.getAll('calendarDays');const raw=await calculateShoppingList(range,{repo});assert.equal(raw.items.length,2);assert.equal(raw.items[0].conceptId,raw.items[1].conceptId);await saveShoppingSettings({departmentOrder:['cereals'],purchaseChoices:[choice]},{repo});const result=await calculateShoppingList(range,{repo});assert.equal(result.items.length,1);assert.equal(result.items[0].quantity,160);assert.equal(result.items[0].conversions[0].factor,0.4);assert.deepEqual(await repo.getAll('calendarDays'),before);const two=await calculateShoppingList({...range,peopleMultiplier:2.5},{repo});assert.equal(two.items[0].quantity,400);});
test('R6 T58 notes/adherence do not stale; increased checked quantity requires verification and preserves manual notes',async()=>{const {repo,registry}=await shopping();let list=await createShoppingChecklist(range,{repo,registry,checklistId:'c'});const item=list.items[0];await updateShoppingChecklistItem('c',item.itemId,{checked:true,notes:'SYNTHETIC NOTE'},{repo,registry});list=await addManualShoppingItem('c',{label:'SYNTHETIC BAGS',itemId:'manual:x'},{repo,registry});const day=await repo.get('calendarDays','d');day.mealSlots[0].notes='SYNTHETIC MEAL NOTE';day.mealSlots[0].adherence='eaten';await repo.put('calendarDays',day);await repo.setMeta('planUpdatedAt','2099-01-01T00:00:00Z');assert.equal((await shoppingChecklistStaleness(list,{repo})).stale,false);day.mealSlots.push({...structuredClone(day.mealSlots[0]),mealOccurrenceId:'m2'});await repo.put('calendarDays',day);assert.equal((await shoppingChecklistStaleness(list,{repo})).stale,true);const refreshed=await refreshShoppingChecklist('c',{repo,registry});const changed=refreshed.items.find(i=>i.itemId===item.itemId);assert.equal(changed.checked,false);assert.equal(changed.quantityChanged,true);assert.equal(changed.notes,'SYNTHETIC NOTE');assert.ok(refreshed.items.some(i=>i.itemId==='manual:x'));assert.equal((await shoppingChecklistStaleness(refreshed,{repo})).stale,false);});
test('R6 T76 departments persist independently from taxonomy and export declares external/manual scope',async()=>{const {repo,registry}=await shopping();await saveShoppingSettings({departmentOrder:['cereals','other'],purchaseChoices:[]},{repo});let list=await createShoppingChecklist(range,{repo,registry,checklistId:'c'});list=await addManualShoppingItem('c',{label:'<script>inert</script>',itemId:'manual:x'},{repo,registry});const text=shoppingText(list,await getShoppingSettings({repo}));assert.match(text,/2026-09-11/);assert.match(text,/esterni ignoti/);assert.match(text,/manuale/);assert.match(text,/150 g/);assert.match(text,/100 g/);const next=await calculateShoppingList({...range,startCivilDate:'2026-09-12',endCivilDate:'2026-09-12'},{repo});assert.equal(next.items.length,0);assert.deepEqual((await getShoppingSettings({repo})).departmentOrder,['cereals','other']);});
test('R6 conversion selection rejects unreviewed and duplicate edges, civil date rejects impossible day',async()=>{const {repo}=await shopping();await assert.rejects(saveShoppingSettings({departmentOrder:[],purchaseChoices:[choice,choice]},{repo}));const edge=(await repo.getAll('ingredientConversions'))[0];edge.reviewStatus='unreviewed';await repo.put('ingredientConversions',edge);await assert.rejects(saveShoppingSettings({departmentOrder:[],purchaseChoices:[choice]},{repo}));await assert.rejects(calculateShoppingList({...range,startCivilDate:'2026-02-30'},{repo}));});
test('R6 T60 self-contained backup restores offline into empty/different catalog including immutable older versions',async()=>{const source=await catalog();const backup=await createBackup(source);assert.equal(backup.formatVersion,4);const dest=new MemoryRepository();await dest.setMeta('activeCatalogVersion','different');await importBackup(backup,{repo:dest,registry:source.registry});assert.deepEqual(await dest.getAll('recipeVersions'),await source.repo.getAll('recipeVersions'));assert.deepEqual(await dest.getAll('ingredientRevisions'),await source.repo.getAll('ingredientRevisions'));assert.equal(await dest.getMeta('activeCatalogVersion'),backup.catalog.catalogVersion);const again=await createBackup({repo:dest,registry:source.registry});assert.deepEqual(again.payload.portableSnapshot,backup.payload.portableSnapshot);});
test('R6 T61 corrupt, missing checksum, orphan and duplicate record reject without mutation',async()=>{const ctx=await catalog();const backup=await createBackup(ctx);const before=await snapshotRepository(ctx.repo);for(const mutate of [d=>d.sha256=null,d=>d.payload.portableSnapshot.recipeVersions[0].ingredientLines[0].ingredientRevisionId='orphan',d=>d.payload.portableSnapshot.ingredients.push(d.payload.portableSnapshot.ingredients[0])]){const b=structuredClone(backup);mutate(b);if(b.sha256)b.sha256=await sha256Json({...b,sha256:null});await assert.rejects(importBackup(b,ctx));assert.deepEqual(await snapshotRepository(ctx.repo),before);}await assert.rejects(validateBackup({...backup,sha256:'0'.repeat(64)},ctx));assert.throws(()=>parseBackupText('{broken'));});
test('R6 T61 immutable ID collision refuses replacement even with valid outer checksum',async()=>{const ctx=await catalog();const backup=await createBackup(ctx);const row=backup.payload.portableSnapshot.recipeVersions[0];row.i18n.it.title='SYNTHETIC CHANGED';backup.sha256=await sha256Json({...backup,sha256:null});await assert.rejects(importBackup(backup,ctx),/Immutable/);});
test('R6 T60 import guards concurrent writes and does not partially restore',async()=>{const ctx=await catalog();const backup=await createBackup(ctx);const original=ctx.repo.atomicMutate.bind(ctx.repo);ctx.repo.atomicMutate=async mutation=>{const theme=(await ctx.repo.getAll('themeProfiles'))[0];theme.fontScale=1.1;await ctx.repo.put('themeProfiles',theme);return original(mutation);};await assert.rejects(importBackup(backup,ctx),/oncurrent/);assert.equal((await ctx.repo.getAll('themeProfiles'))[0].fontScale,1.1);assert.equal(await ctx.repo.getMeta('lastBackupImportAt'),undefined);});
test('R6 T75 diagnostics excludes synthetic profile, notes, stack and arbitrary error text by construction',async()=>{const {repo}=await shopping();await repo.setMeta('secret','SYNTHETIC_SECRET');await repo.put('foodPreferences',{id:'SYNTHETIC_PRIVATE_NAME',notes:'SYNTHETIC_PRIVATE_NOTE'});const text=JSON.stringify(await createLocalDiagnostics({repo,errorCode:'SYNTHETIC_PRIVATE_ERROR'}));assert.doesNotMatch(text,/SYNTHETIC/);assert.match(text,/unspecified/);assert.match(text,/sensitiveDataIncluded":false/);assert.equal(safeExternalUrl('javascript:alert(1)'),null);assert.equal(safeExternalUrl('https://user:password@example.com'),null);assert.equal(safeExternalUrl('https://example.com/source'),'https://example.com/source');});
test('R6 T60 installed bundled catalog exports and validates full frozen reference closure',async()=>{const repo=new MemoryRepository(),r=await registry(),fetcher=fileFetch(path.join(process.cwd(),'public'));await new CatalogImporter({repo,registry:r,fetcher,storage:null}).bootstrap();await ensureBootstrapConfiguration({repo,registry:r,fetcher});const {createInitialPreview,commitGeneratedPreview}=await import('../src/services/effectivePlanService.js');const preview=await createInitialPreview({horizon:{startDate:'2026-09-11',endDate:'2026-09-11'},seed:'r6-portable-history'},{repo,registry:r});assert.equal(preview.status,'success',JSON.stringify(preview.failure));await commitGeneratedPreview(preview,{repo,registry:r});const {migrateRecipePresentation}=await import('../src/services/recipePresentationMigration.js');await migrateRecipePresentation({repo,registry:r});const backup=await createBackup({repo,registry:r});await validateBackup(backup,{repo,registry:r});assert.ok(backup.payload.portableSnapshot.recipeVersions.length>=1800);const dest=new MemoryRepository();await importBackup(backup,{repo:dest,registry:r});assert.equal(await dest.count('recipeVersions'),await repo.count('recipeVersions'));assert.deepEqual(await dest.getAll('calendarDays'),await repo.getAll('calendarDays'));assert.deepEqual(await dest.getAll('operations'),await repo.getAll('operations'));assert.equal(await dest.getMeta('activePlanInstanceId'),preview.planInstance.planInstanceId);const {undoPlanOperation,redoPlanOperation}=await import('../src/services/effectivePlanService.js');await undoPlanOperation(preview.planInstance.planInstanceId,{repo:dest,registry:r});assert.equal(await dest.count('calendarDays'),0);await redoPlanOperation(preview.planInstance.planInstanceId,{repo:dest,registry:r});assert.deepEqual(await dest.getAll('calendarDays'),await repo.getAll('calendarDays'));});
test('R6 legacy backup readers 1 and 2 use matching catalog and restore via atomic boundary',async()=>{for(const version of [1,2]){const ctx=await catalog();const backup=await createBackup(ctx);backup.formatVersion=version;delete backup.payload.portableSnapshot;if(version===1)for(const key of ['foodGroups','ingredientMappings','ingredientConversions','migratedIngredientRevisions','revisionV2State'])delete backup.payload[key];backup.sha256=await sha256Json({...backup,sha256:null});await importBackup(backup,ctx);assert.ok(await ctx.repo.getMeta('backupRecovery'));assert.equal(await ctx.repo.count('recipes'),1);}});
test('R6 T62 connection model rejects obsolete client after versionchange and retries a failed open (not a real two-tab test)',async()=>{const {openDatabase}=await import('../src/db/database.js');let attempts=0,closed=false;const db={close(){closed=true;}};const factory={open(name,version){assert.equal(version,9);const request={};queueMicrotask(()=>{if(attempts++===0){request.error=new Error('injected open failure');request.onerror();}else{request.result=db;request.onsuccess();}});return request;}};await assert.rejects(openDatabase(factory),/injected/);assert.equal(await openDatabase(factory),db);db.onversionchange();assert.equal(closed,true);await assert.rejects(openDatabase(factory),error=>error.code==='upgrade_required');assert.equal(attempts,2);});

test('R6 T61 malicious undo snapshots cannot import arbitrary metadata writes',async()=>{const ctx=await catalog();const backup=await createBackup(ctx);backup.payload.portableSnapshot.operations.push({schemaVersion:1,operationId:'synthetic-op',sequence:1,kind:'synthetic',createdAt:'2026-09-11T00:00:00Z',before:{},after:{metaSet:{activeCatalogVersion:'attacker'}}});backup.sha256=await sha256Json({...backup,sha256:null});await assert.rejects(importBackup(backup,ctx),/Unsafe history metadata/);assert.equal(await ctx.repo.count('operations'),0);});
