import { element } from './dom.js';
import { createIngredientPicker } from './guidedControls.js';
import { markDirty, clearDirty, confirmDiscardChanges } from './uiState.js';
import { ingredientPresentation } from '../domain/ingredientPresentation.js';
import { civilDateInTimeZone } from '../services/effectivePlanService.js';
import { loadProductExtensions, saveExtensionSettings, setRecipeFavorite, saveMenu, createMenuPreview, commitMenuPreview, savePantryEntry, saveSeasonalityProfile, saveIngredientPrice, deleteExtensionRecord, createBatchPreview, commitBatchPreview, deleteProductionBatch } from '../services/productExtensionService.js';
const words=(state,it,en)=>state.i18n.locale==='it'?it:en;
const input=(type,value='',extra={})=>element('input',{type,value:value??'',...extra});
const field=(label,control)=>element('label',{className:'field'},[element('span',{text:label}),control]);
function select(options,value=''){const node=element('select');for(const [id,label] of options)node.append(element('option',{value:id,text:label}));node.value=String(value??'');return node;}
function check(label,value=false){const control=element('input',{type:'checkbox',checked:value});return {control,node:element('label',{className:'check-field'},[control,element('span',{text:label})])};}
function title(state,recipe){return recipe?.i18n?.[state.i18n.locale]?.title||recipe?.i18n?.it?.title||recipe?.i18n?.en?.title||words(state,'Ricetta non disponibile','Recipe unavailable');}
function term(state,id){return state.referenceDataIndex?.term(id)?.i18n?.[state.i18n.locale]?.label||state.referenceDataIndex?.term(id)?.i18n?.it?.label||words(state,'Alimento non disponibile','Food unavailable');}
async function action(state,task,{draft=false,preview=false,navigate=false}={}) {try{if(await task()===false)return;if(preview)return;if(draft)clearDirty(state);if(!navigate)state.notify?.('success',words(state,'Salvato sul dispositivo.','Saved on this device.'));state.render();}catch(error){state.notify?.('error',error.message||String(error));}}
function button(state,it,en,task,{draft=false,danger=false,preview=false,navigate=false}={}){return element('button',{type:'button',className:danger?'button button--danger':'button button--secondary',text:words(state,it,en),onClick:event=>{const b=event.currentTarget;b.disabled=true;void action(state,task,{draft,preview,navigate}).finally(()=>{if(b.isConnected)b.disabled=false;});}});}
function form(state,children,onSave,{preview=false}={}){const f=element('form',{className:'r8-form'},children);const save=element('button',{type:'submit',className:'button',text:words(state,'Salva','Save')});f.append(save);f.addEventListener('input',()=>markDirty(state));f.addEventListener('change',()=>markDirty(state));f.addEventListener('submit',event=>{event.preventDefault();if(!f.reportValidity())return;save.disabled=true;void action(state,onSave,{draft:!preview,preview}).finally(()=>{if(save.isConnected)save.disabled=false;});});return f;}
const routes=[['favorites','Preferiti','Favorites'],['menus','Menu salvati','Saved menus'],['pantry','Dispensa','Pantry'],['batches','Lotti e avanzi','Batches and leftovers'],['seasonality','Stagionalità','Seasonality'],['prices','Prezzi locali','Local prices'],['preferences','Preferenze aggiuntive','Additional preferences']];
export function productExtensionPage(state,tab='favorites') {
  state.r8Ui||={};const section=element('section',{className:'page-card page-card--wide r8-page','data-testid':'product-extensions'},[element('h1',{text:words(state,'Organizza pasti e acquisti','Organize meals and shopping')})]);
  section.append(element('nav',{className:'r8-nav','aria-label':words(state,'Strumenti','Tools')},routes.map(([id,it,en])=>element('a',{href:`/organize/${id}`,'data-route':'',className:'button button--secondary','aria-current':id===tab?'page':null,text:words(state,it,en)}))));
  const body=element('div',{'aria-live':'polite'},[element('p',{text:words(state,'Caricamento…','Loading…')})]);section.append(body);
  void loadProductExtensions(state.repo).then(async ext=>{const needsPlan=['menus','batches'].includes(tab);const plans=needsPlan?await state.repo.getAll('planInstances'):[],days=needsPlan?await state.repo.getAll('calendarDays'):[];const recipeIds=[...new Set([...days.flatMap(d=>d.mealSlots.flatMap(s=>s.recipeComponents.map(c=>c.recipeVersionId))),...ext.productionBatches.map(b=>b.recipeVersionId)])];const recipes=tab==='batches'?await state.repo.getMany('recipeVersions',recipeIds):[];const byVersion=new Map(recipes.map(r=>[r.recipeVersionId,r]));const families=await state.repo.getAll('ingredients');const revisions=new Map((await state.repo.getMany('ingredientRevisions',families.map(f=>f.currentRevisionId))).map(r=>[r.ingredientRevisionId,r]));const items=families.filter(f=>f.status==='active').map(f=>({family:f,revision:revisions.get(f.currentRevisionId)})).filter(i=>i.revision);const ctx={ext,plans,days,recipes,byVersion,items,today:civilDateInTimeZone(state.config.timeZone)};body.replaceChildren();if(tab==='favorites')await favoritesView(state,body,ctx);else if(tab==='menus')menusView(state,body,ctx);else if(tab==='pantry')pantryView(state,body,ctx);else if(tab==='batches')batchesView(state,body,ctx);else if(tab==='seasonality')seasonalityView(state,body,ctx);else if(tab==='prices')pricesView(state,body,ctx);else preferencesView(state,body,ctx);}).catch(error=>body.replaceChildren(element('p',{role:'alert',text:error.message})));return section;
}
async function favoritesView(state,body,{ext}) {
  body.append(element('h2',{text:words(state,'Le tue ricette preferite','Your favorite recipes')}));
  const offset=state.r8Ui.favoriteOffset||0,rows=ext.recipeFavorites.slice(offset,offset+50);
  if(!rows.length)body.append(element('p',{text:words(state,'Aggiungi un preferito dal dettaglio di una ricetta.','Add favorites from recipe details.')}));
  for(const favorite of rows){const family=await state.repo.get('recipes',favorite.recipeId),recipe=family&&await state.repo.get('recipeVersions',family.currentVersionId);body.append(element('article',{className:'r8-row'},[element('a',{href:`/recipes/${encodeURIComponent(favorite.recipeId)}`,'data-route':'',text:title(state,recipe)}),button(state,'Rimuovi preferito','Remove favorite',()=>setRecipeFavorite(favorite.recipeId,false,{repo:state.repo,registry:state.registry}))]));}
  if(offset)body.append(button(state,'Precedenti','Previous',async()=>{state.r8Ui.favoriteOffset=Math.max(0,offset-50);},{navigate:true}));if(offset+50<ext.recipeFavorites.length)body.append(button(state,'Successive','Next',async()=>{state.r8Ui.favoriteOffset=offset+50;},{navigate:true}));
}
function planSelect(state,ctx){return select(ctx.plans.map(p=>[p.planInstanceId,`${p.startDate} → ${p.endDate}`]),state.activePlanInstanceId||ctx.plans.at(-1)?.planInstanceId);}
async function previewDialog(state,preview,onConfirm) {
  const ids=[...new Set(preview.calendarDays.flatMap(d=>d.mealSlots.flatMap(s=>s.recipeComponents.map(c=>c.recipeVersionId))))];const recipes=new Map((await state.repo.getMany('recipeVersions',ids)).map(r=>[r.recipeVersionId,r]));const dialog=element('dialog',{className:'r8-preview','aria-label':words(state,'Anteprima modifiche','Change preview')});let busy=false;
  dialog.append(element('h2',{text:words(state,'Verifica prima di confermare','Review before confirming')}));
  if(preview.menuId)dialog.append(element('p',{text:words(state,'Nei pasti sostituiti saranno azzerate aderenza e note. Puoi annullare dalla cronologia.','Adherence and notes will be cleared in replaced meals. You can undo this from history.')}));
  if(preview.batch)dialog.append(element('p',{text:`${preview.batch.productionDate} · ${preview.batch.portionsProduced} ${words(state,'porzioni prodotte','portions produced')} · ${preview.batch.assignments.length} ${words(state,'assegnate','allocated')} · ${preview.batch.portionsProduced-preview.batch.assignments.length} ${words(state,'residue','remaining')}`}),element('p',{className:'validation-box validation-box--warning',text:preview.batch.storage.status==='unverified'?words(state,'Conservabilità non verificata. Non è stata stimata una durata sicura.','Storage life unverified. No safe duration has been estimated.'):`${preview.batch.storage.useByDate} · ${preview.batch.storage.sourceRef}`}));
  for(const day of preview.calendarDays)dialog.append(element('article',{className:'r8-row'},[element('strong',{text:day.date}),element('ul',{},day.mealSlots.filter(s=>s.mode==='planned').map(slot=>element('li',{text:`${slot.time} · ${slot.recipeComponents.map(c=>title(state,recipes.get(c.recipeVersionId))).join(' + ')}`})))]));
  const status=element('p',{role:'alert'});const cancel=element('button',{type:'button',className:'button button--secondary',text:words(state,'Annulla','Cancel'),onClick:()=>dialog.close()});const confirm=element('button',{type:'button',className:'button',text:words(state,'Conferma','Confirm'),onClick:async()=>{busy=true;confirm.disabled=true;cancel.disabled=true;try{await onConfirm();clearDirty(state);state.notify?.('success',words(state,'Piano aggiornato. Puoi annullare dalla cronologia.','Plan updated. You can undo it from history.'));dialog.close();state.render();}catch(error){status.textContent=error.message;busy=false;confirm.disabled=false;cancel.disabled=false;}}});dialog.append(status,element('div',{className:'button-row'},[cancel,confirm]));dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();});dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();
}
function menusView(state,body,ctx) {
  body.append(element('h2',{text:words(state,'Salva un menu dal piano','Save a menu from your plan')}),element('p',{text:words(state,'Riutilizza le ricette in nuove date: aderenza, note, blocchi e assegnazioni ai lotti non vengono copiati.','Reuse recipes on new dates: adherence, notes, locks and batch allocations are not copied.')}));
  const plan=planSelect(state,ctx),name=input('text','',{required:true,maxLength:100}),start=input('date',ctx.plans.at(-1)?.startDate||ctx.today,{required:true}),end=input('date',ctx.plans.at(-1)?.endDate||ctx.today,{required:true});
  body.append(form(state,[field(words(state,'Nome del menu','Menu name'),name),field(words(state,'Piano di origine','Source plan'),plan),field(words(state,'Dal','From'),start),field(words(state,'Al','To'),end)],()=>saveMenu({name:name.value,planInstanceId:plan.value,startDate:start.value,endDate:end.value},{repo:state.repo,registry:state.registry})));
  for(const menu of ctx.ext.savedMenus){const dest=planSelect(state,ctx),date=input('date',ctx.today,{required:true});body.append(element('article',{className:'r8-row'},[element('h3',{text:`${menu.name} · ${menu.days.length} ${words(state,'giorni','days')}`}),field(words(state,'Piano destinazione','Destination plan'),dest),field(words(state,'Prima data destinazione','First destination date'),date),button(state,'Mostra anteprima','Preview',async()=>{const preview=await createMenuPreview({menuId:menu.menuId,planInstanceId:dest.value,startDate:date.value},{repo:state.repo,registry:state.registry});await previewDialog(state,preview,()=>commitMenuPreview(preview,{repo:state.repo,registry:state.registry}));},{preview:true}),button(state,'Elimina menu','Delete menu',()=>deleteExtensionRecord('savedMenus',menu.menuId,{repo:state.repo}),{danger:true})]));}
}
function pantryView(state,body,ctx) {
  body.append(element('h2',{text:words(state,'Disponibilità in dispensa','Pantry availability')}),element('p',{text:words(state,'Quantità e scadenza sono facoltative. La quantità sconosciuta non riduce la spesa. Scegli esplicitamente le voci da sottrarre nelle Preferenze aggiuntive.','Quantity and expiry are optional. Unknown quantities do not reduce shopping. Explicitly select deductions in Additional preferences.')}));
  const existing=ctx.ext.pantryEntries.find(e=>e.entryId===state.r8Ui.pantryEdit),mode=select([['variant',words(state,'Alimento e forma','Food and form')],['concept',words(state,'Solo alimento, quantità sconosciuta','Food only, unknown quantity')]],existing&&!existing.ingredientId?'concept':'variant');const host=element('div');let picker;
  const buildPicker=()=>{picker=createIngredientPicker(state,state.referenceDataIndex,{mode:mode.value,levels:['concept'],items:ctx.items,value:existing?(mode.value==='variant'?existing.ingredientId:existing.conceptId):null,onChange:()=>markDirty(state)});host.replaceChildren(picker.node);};buildPicker();mode.onchange=()=>{buildPicker();markDirty(state);};
  const amount=input('number',existing?.quantity??'',{min:.001,step:'any'}),unit=select([['g','g'],['ml','ml']],existing?.unit||'g'),expiry=input('date',existing?.expiresOn||''),present=check(words(state,'Presente','Present'),existing?.available??true);
  body.append(form(state,[field(words(state,'Tipo di voce','Entry type'),mode),host,present.node,field(words(state,'Quantità facoltativa','Optional quantity'),amount),field(words(state,'Unità','Unit'),unit),field(words(state,'Scadenza facoltativa','Optional expiry'),expiry)],async()=>{const chosen=picker.getValue(),item=ctx.items.find(i=>i.family.ingredientId===chosen);if(!chosen)throw new Error(words(state,'Scegli un alimento.','Choose a food.'));await savePantryEntry({entryId:existing?.entryId,conceptId:mode.value==='variant'?item?.revision.productTaxonomy?.conceptId:chosen,ingredientId:mode.value==='variant'?chosen:null,available:present.control.checked,quantity:amount.value,unit:unit.value,expiresOn:expiry.value},{repo:state.repo,registry:state.registry});state.r8Ui.pantryEdit=null;}));
  for(const entry of ctx.ext.pantryEntries){const item=ctx.items.find(i=>i.family.ingredientId===entry.ingredientId);body.append(element('article',{className:'r8-row'},[element('strong',{text:`${term(state,entry.conceptId)}${item?' · '+ingredientPresentation(item.revision,state.referenceDataIndex,state.i18n.locale).variant:''}`}),element('span',{text:`${entry.available?words(state,'Presente','Present'):words(state,'Assente','Absent')} · ${entry.quantity===null?words(state,'Quantità sconosciuta','Unknown quantity'):`${entry.quantity} ${entry.unit}`}${entry.expiresOn?' · '+entry.expiresOn:''}`}),button(state,'Modifica','Edit',async()=>{if(!confirmDiscardChanges(state))return false;state.r8Ui.pantryEdit=entry.entryId;},{navigate:true}),button(state,'Elimina','Delete',()=>deleteExtensionRecord('pantryEntries',entry.entryId,{repo:state.repo}),{danger:true})]));}
}
function batchesView(state,body,ctx) {
  body.append(element('h2',{text:words(state,'Una preparazione, più pasti','One preparation, multiple meals')}),element('p',{text:words(state,'Assegna una porzione a ciascun componente già pianificato della stessa versione ricetta. Gli acquisti appartengono alla data di produzione; ogni pasto mantiene i suoi nutrienti e il suo conteggio.','Allocate one portion to each already planned component of the same recipe version. Purchases belong to the production date; every meal keeps its nutrition and frequency count.')}));
  const plan=planSelect(state,ctx),recipeSelect=select([]),produced=input('number',4,{min:1,max:100,step:1,required:true}),date=input('date',ctx.today,{required:true}),storage=check(words(state,'Ho una fonte documentata per la conservazione','I have a documented storage source')),useBy=input('date',''),source=input('text',''),assignments=element('div',{className:'r8-assignments'});let checks=[];
  const refreshRecipes=()=>{const ids=[...new Set(ctx.days.filter(d=>d.planInstanceId===plan.value).flatMap(d=>d.mealSlots.flatMap(s=>s.recipeComponents.map(c=>c.recipeVersionId))))];recipeSelect.replaceChildren(...ids.map(id=>element('option',{value:id,text:title(state,ctx.byVersion.get(id))})));refreshAssignments();};
  const refreshAssignments=()=>{checks=[];assignments.replaceChildren();for(const day of ctx.days.filter(d=>d.planInstanceId===plan.value))for(const slot of day.mealSlots)for(const [componentIndex,c] of slot.recipeComponents.entries())if(c.recipeVersionId===recipeSelect.value&&!slot.locked&&!c.productionBatchId){const box=check(`${slot.civilDate} · ${slot.time} · #${componentIndex+1} · ${title(state,ctx.byVersion.get(c.recipeVersionId))}`);checks.push({box,assignment:{calendarDayId:day.calendarDayId,mealOccurrenceId:slot.mealOccurrenceId,componentIndex}});assignments.append(box.node);}};
  plan.onchange=refreshRecipes;recipeSelect.onchange=refreshAssignments;refreshRecipes();
  const f=form(state,[field(words(state,'Piano','Plan'),plan),field(words(state,'Ricetta pianificata','Planned recipe'),recipeSelect),field(words(state,'Porzioni prodotte','Portions produced'),produced),field(words(state,'Data di produzione','Production date'),date),storage.node,field(words(state,'Utilizzabile fino al (solo con fonte)','Use by (with source only)'),useBy),field(words(state,'Fonte della conservazione','Storage source'),source),element('h3',{text:words(state,'Pasti a cui assegnare una porzione','Meals receiving one portion')}),assignments],async()=>{const chosen=checks.filter(x=>x.box.control.checked).map(x=>x.assignment);if(!chosen.length)throw new Error(words(state,'Seleziona almeno un consumo.','Select at least one consumption.'));const preview=await createBatchPreview({planInstanceId:plan.value,recipeVersionId:recipeSelect.value,portionsProduced:produced.value,productionDate:date.value,storage:storage.control.checked?{status:'documented',useByDate:useBy.value,sourceRef:source.value}:{status:'unverified',useByDate:null,sourceRef:null},assignments:chosen},{repo:state.repo,registry:state.registry});await previewDialog(state,preview,()=>commitBatchPreview(preview,{repo:state.repo,registry:state.registry}));},{preview:true});f.lastChild.textContent=words(state,'Verifica anteprima lotto','Review batch preview');body.append(f);
  for(const batch of ctx.ext.productionBatches)body.append(element('article',{className:'r8-row'},[element('h3',{text:title(state,ctx.byVersion.get(batch.recipeVersionId))}),element('p',{text:`${batch.productionDate} · ${batch.portionsProduced} ${words(state,'porzioni','portions')} · ${batch.assignments.length} ${words(state,'assegnate','allocated')} · ${batch.portionsProduced-batch.assignments.length} ${words(state,'residue','remaining')}`}),element('p',{className:'muted',text:batch.storage.status==='unverified'?words(state,'Conservabilità non verificata','Storage life unverified'):`${batch.storage.useByDate} · ${batch.storage.sourceRef}`}),element('ul',{},batch.assignments.map(a=>{const day=ctx.days.find(d=>d.calendarDayId===a.calendarDayId),slot=day?.mealSlots.find(s=>s.mealOccurrenceId===a.mealOccurrenceId);return element('li',{},[element('a',{href:`/calendar/day?date=${day?.date||a.civilDate}`,'data-route':'',text:`${a.civilDate} · ${slot?.time||''}`})]);})),button(state,'Scollega e rimuovi lotto','Detach and remove batch',()=>deleteProductionBatch(batch.batchId,{repo:state.repo,registry:state.registry}),{danger:true})]));
}
function seasonalityView(state,body,ctx) {
  body.append(element('h2',{text:words(state,'Stagionalità della tua area','Seasonality for your area')}),element('p',{text:words(state,'Aggiungi mesi e fonte per ogni alimento. Non viene applicato un calendario nazionale predefinito. L’area selezionata influisce solo sulla preferenza soft.','Add months and a source for each food. No default national calendar is imposed. The selected area only affects a soft preference.')}));
  const profile=select([['',words(state,'Nuova area','New area')],...ctx.ext.seasonalityProfiles.map(p=>[p.profileId,p.name])]);const name=input('text','',{required:true,maxLength:100});profile.onchange=()=>{name.value=ctx.ext.seasonalityProfiles.find(p=>p.profileId===profile.value)?.name||'';markDirty(state);};const picker=createIngredientPicker(state,state.referenceDataIndex,{mode:'concept',levels:['concept'],items:ctx.items,onChange:()=>markDirty(state)});const monthChecks=Array.from({length:12},(_,n)=>check(new Intl.DateTimeFormat(state.i18n.locale,{month:'long',timeZone:'UTC'}).format(new Date(Date.UTC(2026,n,1)))));const source=input('text','',{required:true}),reviewedOn=input('date',ctx.today,{required:true}),verified=check(words(state,'Ho verificato mesi e fonte per questa area','I checked the months and source for this area'));
  body.append(form(state,[field(words(state,'Profilo area','Area profile'),profile),field(words(state,'Nome area','Area name'),name),picker.node,element('div',{className:'r8-months'},monthChecks.map(c=>c.node)),field(words(state,'Fonte','Source'),source),field(words(state,'Data verifica','Review date'),reviewedOn),verified.node],()=>{if(!verified.control.checked)throw new Error(words(state,'Conferma la verifica dei dati.','Confirm the data review.'));const conceptId=picker.getValue();if(!conceptId)throw new Error(words(state,'Scegli un alimento.','Choose a food.'));const existing=ctx.ext.seasonalityProfiles.find(p=>p.profileId===profile.value);return saveSeasonalityProfile({profileId:existing?.profileId,name:name.value,entries:[...(existing?.entries||[]).filter(e=>e.conceptId!==conceptId),{conceptId,months:monthChecks.flatMap((c,n)=>c.control.checked?[n+1]:[]),sourceRef:source.value,reviewedAt:reviewedOn.value}]},{repo:state.repo,registry:state.registry});}));
  for(const area of ctx.ext.seasonalityProfiles)body.append(element('article',{className:'r8-row'},[element('h3',{text:area.name}),...area.entries.map(e=>element('p',{text:`${term(state,e.conceptId)} · ${e.months.join(', ')} · ${e.sourceRef} · ${e.reviewedAt}`})),button(state,'Elimina area','Delete area',()=>deleteExtensionRecord('seasonalityProfiles',area.profileId,{repo:state.repo}),{danger:true})]));
}
function pricesView(state,body,ctx) {
  body.append(element('h2',{text:words(state,'Prezzi documentati','Documented prices')}),element('p',{text:words(state,'Inserisci prezzo, quantità di riferimento e data. Un prezzo mancante resta sconosciuto. Il riepilogo dei costi e il budget compaiono nella Spesa.','Enter price, reference quantity and date. Missing prices remain unknown. Cost and budget summaries appear in Shopping.')}));
  const picker=createIngredientPicker(state,state.referenceDataIndex,{mode:'variant',items:ctx.items,onChange:()=>markDirty(state)}),price=input('number','',{min:0,step:.01,required:true}),amount=input('number',1000,{min:.001,step:'any',required:true}),unit=select([['g','g'],['ml','ml']],'g'),currency=select(['EUR','USD','GBP'].map(c=>[c,c]),ctx.ext.settings.currency),date=input('date',ctx.today,{required:true}),source=input('text','',{required:true});
  body.append(form(state,[picker.node,field(words(state,'Prezzo','Price'),price),field(words(state,'Valuta','Currency'),currency),field(words(state,'Quantità a quel prezzo','Quantity at that price'),amount),field(words(state,'Unità','Unit'),unit),field(words(state,'Data rilevazione','Observation date'),date),field(words(state,'Fonte o negozio','Source or store'),source)],()=>saveIngredientPrice({ingredientId:picker.getValue(),price:price.value,quantity:amount.value,unit:unit.value,currency:currency.value,observedOn:date.value,sourceRef:source.value},{repo:state.repo,registry:state.registry})));
  for(const row of ctx.ext.ingredientPrices){const item=ctx.items.find(i=>i.family.ingredientId===row.ingredientId);const label=item?ingredientPresentation(item.revision,state.referenceDataIndex,state.i18n.locale):null;body.append(element('article',{className:'r8-row'},[element('strong',{text:label?`${label.name} · ${label.variant}`:words(state,'Forma archiviata','Archived form')}),element('span',{text:`${row.price} ${row.currency} / ${row.quantity} ${row.unit} · ${row.observedOn} · ${row.sourceRef}`}),button(state,'Rimuovi prezzo','Remove price',()=>deleteExtensionRecord('ingredientPrices',row.priceId,{repo:state.repo}),{danger:true})]));}
}
function preferencesView(state,body,ctx) {
  const settings=ctx.ext.settings;body.append(element('h2',{text:words(state,'Scegli cosa utilizzare','Choose what to use')}),element('p',{text:words(state,'Queste preferenze non possono superare allergie, esclusioni o vincoli del piano. Il budget è informativo e riguarda il periodo di spesa selezionato.','These preferences cannot override allergies, exclusions or plan constraints. The budget is informational and applies to the selected shopping period.')}));
  const favorite=input('number',settings.favoriteWeight,{min:0,max:5,step:.5,required:true}),area=select([['',words(state,'Nessuna','None')],...ctx.ext.seasonalityProfiles.map(p=>[p.profileId,p.name])],settings.seasonalityProfileId||''),season=input('number',settings.seasonalityWeight,{min:0,max:5,step:.5,required:true}),currency=select(['EUR','USD','GBP'].map(c=>[c,c]),settings.currency),stale=input('number',settings.priceStaleDays,{min:1,max:365,step:1,required:true}),budget=input('number',settings.shoppingBudget??'',{min:.01,step:.01});const pantry=ctx.ext.pantryEntries.map(entry=>({entry,box:check(`${term(state,entry.conceptId)}${entry.ingredientId?' · '+ingredientPresentation(ctx.items.find(i=>i.family.ingredientId===entry.ingredientId)?.revision,state.referenceDataIndex,state.i18n.locale).variant:''} · ${entry.quantity===null?words(state,'Quantità sconosciuta: non sottratta','Unknown quantity: not deducted'):`${entry.quantity} ${entry.unit}`}`,settings.pantryEntryIds.includes(entry.entryId))}));
  body.append(form(state,[field(words(state,'Priorità preferiti (0 disattiva, 5 massima)','Favorite priority (0 off, 5 highest)'),favorite),field(words(state,'Area stagionale','Seasonal area'),area),field(words(state,'Priorità stagionalità (0 disattiva, 5 massima)','Seasonality priority (0 off, 5 highest)'),season),element('h3',{text:words(state,'Dispensa da sottrarre alla spesa','Pantry to deduct from shopping')}),...pantry.map(p=>p.box.node),field(words(state,'Valuta dei costi','Cost currency'),currency),field(words(state,'Segnala prezzi più vecchi di questi giorni','Flag prices older than these days'),stale),field(words(state,'Budget facoltativo per il periodo di spesa','Optional budget for the shopping period'),budget)],()=>saveExtensionSettings({favoriteWeight:Number(favorite.value),seasonalityProfileId:area.value||null,seasonalityWeight:Number(season.value),pantryEntryIds:pantry.filter(p=>p.box.control.checked).map(p=>p.entry.entryId),currency:currency.value,priceStaleDays:Number(stale.value),shoppingBudget:budget.value===''?null:Number(budget.value)},{repo:state.repo})));
}
